### PR TITLE
Add axis_option argument for matplotlib plots

### PR DESCRIPTION
**Pull request by mkaze**
This PR addresses #38 for matplotlib plots (i.e. `plot` method of `Embedding` and `EmbeddingSet`).

### CODE REVIEW

**Comment by mkaze** [comment]
The thing that amazes me the most is that it's been a week now and this issue has not been resolved yet (whether it's Github Actions or PyPI server)!

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @akelad will take a look at it as soon as possible ✨

**Comment by koaning** [comment]
Urgh. This is getting annoying I agree. This time it seems to be tensorflow that is having trouble getting the proper installation. I wonder what is causing this.

**Comment by koaning** [comment]
I'm guessing that it might be a pip issue, looking at their updates on pypi. It all seems very [recent](https://pypi.org/project/pip/#history).

**Comment by mkaze** [comment]
@koaning It seems it happens even if we use `wget` to download the package wheels: https://github.com/actions/virtual-environments/issues/1354#issuecomment-669911376

**Comment by koaning** [comment]
Urgh. I guess we'll need to wait for a fix then. Good to confirm this lies outside of our control tho.

**Comment by koaning** [comment]
This is a nice one to merge because I had need of it today. I'll be ignoring the tests for now because of the flaky pip/github actions situations. Again, @mkaze thanks!

**Pull request merged**
