### PR TITLE
fixed small typos

### PR DESCRIPTION
**Pull request by Ayushsunny**
Fixed all the typos where **blue** was written as **bluee** mentioned on this issue code #177

### CODE REVIEW

**Comment by koaning** [comment]
https://github.com/RasaHQ/whatlies/issues/177

**Comment by koaning** [comment]
Hi @Ayushsunny the change looks good to me. Before moving on to the merge step, could you confirm the CLA?

**Comment by Ayushsunny** [comment]
> Hi @Ayushsunny the change looks good to me. Thanks!
> 
> Before moving on to the merge step, could you confirm the CLA?

Yes @koaning Sir, I have completed that step

**Comment by Ayushsunny** [comment]
> > Hi @Ayushsunny the change looks good to me. Thanks!
> > Before moving on to the merge step, could you confirm the CLA?
> 
> Yes @koaning Sir, I have completed that step

Screenshot from 2021-04-23 13-07-52

**Comment by koaning** [comment]
@Ayushsunny could you scroll down to the bottom of the page? It might be that there's a delay from our CLA tool, but it's strange that it's not updating.

**Comment by koaning** [comment]
@Ayushsunny could you confirm what you see here? 

image

**Comment by Ayushsunny** [comment]
> @Ayushsunny could you confirm what you see here?
> 
> image

Yes It's asking to sign CLA that I have already signed

**Comment by koaning** [comment]
My colleague thinks that you either didn't set an email with git on your machine or that they set an email address, but it isn't added to your github account.

Could you try running this locally;

```
git config --global <YOUR EMAIL HERE>
```

Once you've set up proper email, you can make a new PR on a new branch. Once you've done that, the CLA should pick it up again.

**Comment by Ayushsunny** [comment]
> My colleague thinks that you either didn't set an email with git on your machine or that they set an email address, but it isn't added to your github account.
> 
> Could you try running this locally;
> 
> ```
> git config --global <YOUR EMAIL HERE>
> ```
> 
> Once you've set up proper email, you can make a new PR on a new branch. Once you've done that, the CLA should pick it up again.

okay Sir I'll make a new PR, Thank you for the info.
I am closing this PR

**Pull request closed without merging**
