### PR TITLE
Add Hugging Face Transformers language class

### PR DESCRIPTION
**Pull request by mkaze**
This PR addresses #12 and implements `HFTransformersLanguage` class to support Hugging Face Transformer models. It's an initial implementation, with room for adding more features and custom configs. Currently, the embedding vector is obtained by summing the token representations (excluding special tokens, e.g. [CLS] or [SEP]).

Further, we have added `torch` as a **development dependency** so that we can test this class on both TensorFlow as well as PyTorch.

### CODE REVIEW

**Comment by mkaze** [comment]
The checks should be re-run to see if the error in installing the package is resolved. If not, probably the hash in the cache is outdated and should be ignored with `--no-cache-dir` flag.

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by mkaze** [comment]
@koaning As you may want, I removed large models from the tests of this class as well and replaced them with smaller models (~2MB). However, the error in installing torch is still there in Github actions.

**Comment by koaning** [comment]
I've reset the job three times now. On the third time it passed. Dunno what caused it. Is this common?

**Comment by mkaze** [comment]
@koaning No, I haven't seen such thing before (though, I don't use Github Actions a lot). Two times, it broke on installing torch due to hash conflict of downloaded wheel file. I don't why?!

logs

**Comment by koaning** [comment]
My collegues are suggesting that github is having issues today that might also be causing some of this. I'll check again tomorrow morning. If it looks green, I'll merge.

**Comment by mkaze** [comment]
@koaning All right, but I think the last run completed successfully with no errors (it's showing all green to me).

**Comment by koaning** [comment]
Just re-ran everything and it ran fine. Cool.

**Pull request merged**
