### PR TITLE
Fix #194: Change Internal Filenames

### LINKED ISSUE #194: Rename internal files to prevent import errors.
Testing the examples in Notebook, I'm encountering an error on the UMAP example.  Any ideas?

```from whatlies.transformers import pca, umap

# orig_chart = emb.plot_interactive('man', 'woman')
pca_plot = emb.transform(pca(2)).plot_interactive('pca_0', 'pca_1')

emb.transform(umap(2)).plot_interactive('umap_0', 'umap_1')
```

```TypeError                                 Traceback (most recent call last)
<ipython-input-5-18f8db210390> in <module>
      2 
      3 # orig_chart = emb.plot_interactive('man', 'woman')
----> 4 pca_plot = emb.transform(pca(2)).plot_interactive('pca_0', 'pca_1')
      5 
      6 emb.transform(umap(2)).plot_interactive('umap_0', 'umap_1')

TypeError: 'module' object is not callable```

### PR DESCRIPTION
**Pull request by koaning**
People were important `pca` instead of `Pca` by accident. To prevent that I've added an `_` prefix to all the transformer/language filenames. This should prevent a lot of buggery. 

Original issue: https://github.com/RasaHQ/whatlies/issues/194

### CODE REVIEW

**Comment by koaning** [comment]
I have a feeling that **bpemb** is blocking traffic from some of the github IP adresses.

```
Max retries exceeded with url: /bpemb/en/en.wiki.bpe.vs10000.d100.w2v.bin.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15ad072b0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```

This caused a test to fail. I've refactored it now to use the local embeddings instead.

**Comment by koaning** [comment]
@mkaze agree with this change? I prefer to merge this ASAP to prevent any merge conflicts.

**Comment by mkaze** [comment]
@koaning Yeah, sure! Looks good to me. That's a style choice and one way of resolving the problem, anyways.

**Comment by koaning** [comment]
Sweet. It seemed like a simple way to adress and it's something I've seen other packages do as well.

**Pull request merged**
