### PR TITLE
Automated Tests on Documentation

### PR DESCRIPTION
**Pull request by koaning**
This is the first step to automate our docs a bit more. We're now parsing the docstrings and checking if they cause an error. 

Turns out ... they no longer do.

### CODE REVIEW

**Comment by mkaze** [comment]
I think you can even safely remove the OS check for installing `torch` as `pip install torch` should work for both.

**Comment by koaning** [comment]
I'll check that! I think for this PR it may be better to only add the tests for the apidoc. The tutorial docs contain really heavy language backends.

**Comment by koaning** [comment]
Mhm. It's getting back to flaky behavior again. 

image

**Comment by koaning** [comment]
I'll restart the workflow to make sure it's not a github actions hiccup. If the slowness persists I'll revert back to the original torch install to see if it makes a difference.

**Pull request merged**
