### PR TITLE
Update embeddingset.py

### PR DESCRIPTION
**Pull request by Raghibshams456**
this will give red background color ..of plot_interactive

### CODE REVIEW

**Comment by Raghibshams456** [comment]
@koaning please have look....

**Comment by Raghibshams456** [comment]
@koaning  can u tell where I have gone wrong...
I have done this changes in my code
Screenshot from 2020-07-13 23-27-06

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @koaning will take a look at it as soon as possible ✨

**Comment by Raghibshams456** [comment]
I have done something wrong...silly mistake...will try agin

**Pull request closed without merging**
